services:
  db:
    image: postgres:16-alpine
    container_name: live-chat-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 
      POSTGRES_DB: live-chat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Décommente la ligne ci-dessous si tu as un fichier SQL à exécuter au premier démarrage :
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d live-chat"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: node:20-alpine
    container_name: live-chat-backend
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      # Variable d'environnement pour connecter Node.js à la base
      DATABASE_URL: "postgres://admin:root@db:5432/live-chat"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: node:20-alpine
    container_name: live-chat-frontend
    working_dir: /app/frontend
    volumes:
      - .:/app
    command: sh -c "cd /app/frontend && npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"

volumes:
  pgdata: